version: '3.8'

services:

  tes-service:
    build: .
    container_name: tes-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://apollo.intercars.local:1433;databaseName=TrackIT;encrypt=true;trustServerCertificate=true;
      - SPRING_DATASOURCE_USERNAME=cdcservic3
      - SPRING_DATASOURCE_PASSWORD=8j4x8kXv4NNBWVw
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=10.105.0.188:9092
    networks:
      - kafka-oms_network

networks:
  kafka-oms_network:
    external: true
