spring:
  application:
    name: TES
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: tes-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:sqlserver://apollo.intercars.local:1433;databaseName=TrackIT;encrypt=true;trustServerCertificate=true;
    username: cdcservic3
    password: 8j4x8kXv4NNBWVw
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG
